version: "3.9"
services:
  csvserver:
    image: infracloudio/csvserver
    container_name: csvserver
    ports:
      - "9393:9300"
    volumes:
      - ${PWD}/inputFile:/csvserver/inputdata
    env_file:
      - csvserver.env

  prometheus:
    image: prom/prometheus:v2.22.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ${PWD}/prometheus.yaml:/etc/prometheus/prometheus.yml
    links:
      - "csvserver"
